package com.artificery.BobShopBooksAPI.enums;

public enum FilterOperator {
    EQUAL, NOT_EQUAL, GREATER_THAN, SMALLER_THAN, GREATER_OR_EQUAL_TO, SMALLER_OR_EQUAL_TO, CONTAINS, NOT_CONTAINS,
    LIST_CONTAINS, LIST_CONTAINS_PARTIAL, LIST_NOT_CONTAINS, LIST_NOT_CONTAINS_PARTIAL;
}
